# Generated by Django 4.1.7 on 2023-03-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_postsmodel_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='authormodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
